name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支，可以根据需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 根据需要选择 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm  # 安装 pnpm

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装依赖

      - name: Build the project
        run: pnpm run build  # 使用 pnpm 构建项目

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 构建输出目录 